@startuml
''' 省略底部

left to right direction

	boundary ProviderInterface 
	control ProviderController 
	entity OrderList

	ProviderInterface -- ProviderController
	ProviderController -- OrderList

@enduml