@startuml

start
:打开用户管理页面,修改指定用户信息;
:在筛选框中，输入用户名选择用户;
if (用户存在?) then (是)
    :管理员选择该用户;
    :点击编辑按钮，查看用户信息表单;
    :修改特定属性,按下提交按钮确认修改;
    if (确认修改) then (是)
        :数据更新到数据库中，并返回到用户列表;
    else (否);
        :提示框消失，继续修改;
    endif
else (否)
    :该用户不存在，无法修改信息;
endif
stop
@enduml