@startuml

start
:打开用户管理页面,删除指定用户信息;
:在筛选框中，输入用户名选择用户;
if (用户存在?) then (是)
    :管理员选择该用户;
    :点击删除按钮;
    :弹出提示框确认修改;
    if (确认修改) then (是)
        :删除操作更新到数据库中，并返回到用户列表;
    else (否);
        :提示框消失，返回到用户列表;
    endif
else (否)
    :该用户不存在，无法删除;
endif
stop
@enduml