' @startuml
' left to right direction
' skinparam packageStyle rectangle
' ' skinparam roundcorner 80
' actor 企业
' actor 生产商
' actor 信用系统
' actor 管理员
' rectangle 鲜天下（版本一） {
'   企业 -- (注册)  
'   企业 -- (发起订单)
'   企业 -- (查看订单)
'   企业 -- (修改订单) 
'   (审核订单) -- 管理员
'   (资金管理) -- 管理员
'   (注册) -- 管理员
'   (订单推送) -- 管理员
'   (查看订单) -- 管理员
'   生产商 -- (接收订单)
'   生产商 -- (注册)
'   生产商 -- (查看订单) 
'   (资金管理) -- 信用系统
 
' }
' @enduml


@startuml
left to right direction
skinparam packageStyle rectangle
' skinparam roundcorner 80
actor 企业
actor 生产商
actor 管理员
actor 资金及授信系统
rectangle 鲜天下（版本二） {
  企业 -- (注册)  
  企业 -- (登陆) 
  企业 -- (发起订单)
  企业 -- (支付货款)
  企业 -- (查看发布订单)
  企业 -- (修改订单) 
  (订单处理) -- 管理员
  (登陆) -- 管理员
  (注册) -- 管理员
  (查看所有订单) -- 管理员
  (支付货款) -- 资金及授信系统
  (订单处理) -- 资金及授信系统
  (申请资金) -- 资金及授信系统
  生产商 -- (接收订单)
  生产商 -- (申请资金)
  生产商 -- (注册)
  生产商 -- (查看接收订单) 
}
@enduml
