@startuml
left to right direction
skinparam packageStyle rectangle
' skinparam roundcorner 80
actor 企业
actor 生产商
actor 信用系统
actor 管理员
rectangle 鲜天下（版本一） {
  企业 -- (注册)  
  企业 -- (发起订单)
  企业 -- (查看订单)
  企业 -- (修改订单) 
  (审核订单) -- 管理员
  (资金管理) -- 管理员
  (注册) -- 管理员
  (订单推送) -- 管理员
  (查看订单) -- 管理员
  生产商 -- (接收订单)
  生产商 -- (注册)
  生产商 -- (查看订单) 
  (资金管理) -- 信用系统
 
}
@enduml


@startuml
left to right direction
skinparam packageStyle rectangle
' skinparam roundcorner 80
actor 企业
actor 生产商
actor 信用系统
actor 管理员
actor 授信系统
rectangle 鲜天下（版本二） {
  企业 -- (注册)  
  企业 -- (发起订单)
  企业 -- (支付定金)
  企业 -- (查看订单)
  企业 -- (修改订单) 
  (审核订单) -- 管理员
  (资金管理) -- 管理员
  (注册) -- 管理员
  (订单推送) -- 管理员
  (查看订单) -- 管理员
  生产商 -- (接收订单)
  生产商 -- (申请资金)
  生产商 -- (注册)
  生产商 -- (查看订单) 
  (审核订单) -- 授信系统
  (发起订单) .> (审核订单) : include
  (修改订单) .> (审核订单) : include
  (接收订单) .> (审核订单) : include
  (申请资金) .> (资金管理) : include
  (支付定金) .> (资金管理) : include
}
@enduml
