@startuml

start
:打开用户管理页面,进行新用户审核;
if (如果存在需要审核的用户?) then (是)
    :管理员选择其中一个新用户;
    :点击查看详情按钮，查看用户信息;
    if (信息合格) then (是)
        :向新用户账号标记为通过;
    else (否)
        :向新用户账号标记为不通过;
    endif
else (否)
    :不需要进行新用户的审核;
endif
stop
@enduml