@startuml

start
:输入订单名字;
:输入订单概要;
:输入订单地址;
:设置订单截止日期;
if (截止日期是否合法?) then (是)
    :输入订单单价;
    if (订单单价输入合法?) then (是)
        :输入订单数量;
        if (订单数量输入合法?) then (是)
            :点击提交按钮;
            :提示成功发布母订单;
        else (否)
            :提示订单数量输入不合法;
        endif
    else (否)
        :提示订单单价输入不合法;
    endif
else (否)
    :提示截止日期不合法;
endif
stop
@enduml