@startuml
''' Layout
start
:微供应商填写可供应数量信息、备注和联系方式;
if (信息是否合法) then (是)
	:微供应商点击提交按钮;
	:平台弹出再次确认界面;
	if (用户是否再次确认) then (是)
		:平台提示用户成功加入母订单;
		:用户选择过滤条件或排序条件;
		:平台显示过滤或排序结果;
	else (否)
		:平台提示此次提交取消;
	endif
else (否)
	:平台提示信息错误原因;
endif

stop
@enduml