@startuml

start
:用户点击提现按钮;
:平台显示用户余额;
:用户输入提现金额;
if (提现金额小于余额) then (是)
	:用户输入密码;
	if (密码正确) then (是)
	:平台更改用户信息\n并返回成功提现信息;
	else (否)
	:平台输出密码错误信息;
	endif
else (否)
:平台输出用户余额不足信息;
endif
stop

@enduml