@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor Admin as act
	boundary AuditInterface as bou
	control AuditController as con
	database OrderList as db

	autonumber
	act -> bou : getOrderInfo()
	bou -> con : getOrderInfo()
	con -> db : queryOrderInfo()
	db --> con : returnResult
	con -> bou : orderInfo()
	bou -> bou : displayOrderInfo()
	act -> bou : verify()
	bou -> con : verify()
	con -> db : update()
	db --> con : returnTrue
	con -> bou : verificationInfo()
	bou -> bou : displayResult()

@enduml