@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor Admin as act
	boundary AuditInterface as bou
	control AuditController as con
	database UserList as db

	autonumber
	act -> bou : getUserInfo()
	bou -> con : getUserInfo()
	con -> db : queryUserInfo()
	db --> con : returnResult
	con -> bou : UserInfo()
	bou -> bou : displayUserInfo()
	act -> bou : verify()
	bou -> con : verify()
	con -> db : update()
	db --> con : returnTrue
	con -> bou : verificationInfo()
	bou -> bou : displayResult()

@enduml