@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor User as act
	boundary CommitInterface as bou
	control CommitController as con
	database OrderList as db

	autonumber
	act -> bou : fillCommitInfo()
	bou -> con : getInfo()
	con -> db : createTmpOrder()
	db --> con : returnTrue 
	con -> bou : commitResult()
	bou -> bou : display()

@enduml