@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor Provider as act
	boundary ProviderInterface as bou
	control ProviderController as con
	database OrderList as db

	autonumber
	act -> bou : joinEvent()

	activate bou
	bou -> con : join()

	activate con
	con -> db : insert()

	activate db
	db --> con : returnResult

	deactivate db
	con --> bou : returnResult

	deactivate con
	bou -> bou : display()

@enduml