@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor User as act
	boundary UserInterface as bou
	control UserController as con
	database UserList as db

	autonumber
	act -> bou : loginEvent()
	activate bou

	bou -> con : login()
	activate con 

	con -> db : query()
	activate db

	db --> con : ReturnResult
	deactivate db

	con --> bou : ReturnResult
	deactivate con

	bou -> bou : display()

@enduml