@startuml
''' 省略底部
	hide footbox 

''' 定义类
	actor User as act
	boundary UserInterface as bou
	control UserController as con
	database MainOrderList as db

	autonumber
	act -> bou : queryEvent()
	activate bou

	bou -> con : queryMainOrder()
	activate con

	con -> db :  query()
	activate db

	db --> con : returnResult
	deactivate db

	con -> bou : queryResult()
	deactivate con

	bou -> bou : display()

@enduml