@startuml

start
:打开子订单管理页面;
:管理员按下每个订单的查看详情按钮，检查订单是否有效;
if (订单无效?) then (是)
    :管理员选择该订单;
    :点击取消按钮;
    :弹出提示框确认修改;
    if (确认取消) then (是)
        :取消操作更新到数据库中，并返回到母订单列表;
    else (否);
        :提示框消失，返回到子订单列表;
    endif
else (否)
    :该子订单有效;
endif
stop
@enduml