@startuml
''' Layout
start
:请求用户输入所需额度;
if (请求额度<=总额度?) then (是)
    :请求用户确认;
    if (用户确认?) then (是)
        :扣除申请配额;
        :保存订单;
        :显示申请成功;
    else (否)
        :显示申请取消;
    endif
else (否)
    :显示申请失败;
endif
stop
@enduml